// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SearchTest : BasePage {
  
  LoginPage loginPage;
  SearchPage searchPage;
    
  

  [OneTimeSetUp]
  public void SetUp() {
    Initialize();
    loginPage = new LoginPage(driver);
    searchPage= new SearchPage(driver);
  }

  [Test]
  public void test1_login() {
    //giriş yapılma testi
  
        loginPage.login();
        Assert.True(driver.FindElement(By.XPath("//h2[contains(.,\'Good\')]")).Displayed);
        
  }


 [Test]
  public void test2_search() {
    //giriş yapılıp, aranan kelime ile eş olan artiste tıklanma kontrölü
    loginPage.login();
    searchPage.search();
  Assert.That(driver.FindElement(By.XPath("//h1[contains(.,\'Duman\')]")).Text, Is.EqualTo(searchPage.search_word));

  }  


 [OneTimeTearDown]
  public void CloseDriver() {
    TearDown();
  }


}
